### ISSUE TITLE
Create a cache driver to store workflow results

### ISSUE THREAD

**Issue by Charles546** [honeydipper/honeydipper#226]
A cache layer might help combat some of the rate limiting issues we are seeing with some of the service providers such as `whoisoncall` from OpsGenie. We might want do something like

```
steps:
  - call_function: opsgenie.whoisoncall
    cache:
      - key: opsgenie_whoisoncall
        expiring: 900
  - call_workflow: notify
    # show result in slack
```
