### ISSUE TITLE
Proposal: an abstract "scenario" definition

### ISSUE THREAD

**Issue by Charles546** [honeydipper/honeydipper#41]
"Scenario" is the counter part of "workflow" on the triggering side.  Our rule should use "scenario"  instead of "trigger" to define "when" to take action.  This allows Honeydipper rules to be more flexible and accurate.  Also, each "scenario" can have a output data that can be computed using go template and interpolation, which really make the "scenarios" abstract, similar to "wfdata" on workflow side.

Some example

1) The simplest scenario is just a trigger

```
---
scenarios:
  sample:
    type: trigger
    data:
      output: '{{ .event.json.path.field }}'
    content:
      source:
        system: mysystem
        trigger: mytrigger
```

2) any of
```
---
scenarios:
  another:
    type: any
    conent:
      - content: scenario1
      - content: scenario2
      ...
```

3) type all
```
scenarios
  all_should_happen:
    type: all
    within: '3m'
    content:
       - content: scenario1
       - content: scenario2
       ...
```

4) type: sequence ...
