### ISSUE TITLE
Conditional asset loading using go template

### ISSUE THREAD

**Issue by Charles546** [honeydipper/honeydipper#496]
Honeydipper already uses go template for string interpolation. However, since it is **inline template**, it only affects string values. We can't use that to load assets conditionally. Being able to load assets conditionally can be very useful when we sharing config repos between environments. For example, imaging we added the global template feature with `<%` and `%>` marker, we can load a rule or a system based on the environment.

```yaml
---
rules:
<% if eq .env.environment "prod" %>
  - when:
      target:
        system: internal
        trigger: pubsub
      if_match:
        json:
          event: deploy_app_prod
    do:
      call_workflow: deploy_prod
<% end %>
... other rules...
```
Or something like
```yaml
system:
  github_app:
    extends:
      - github
    data:
      signingSecret: LOOKUP[gcloud-secret,<% .env.gcp_project %>/github_signing_secret
```

The normal context variables, event data and labels will not be available during the render of the file because it is rendered at file loading time. But, environment variables, ip addresses, CLI parameters should be available.
